### ISSUE TITLE
Please Add @dwyl as Co-owner of b58 Hex.pm Package 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/base58#15]
Hi @SimonLab! 
On Monday when you are back at your desk, 
could you please add [@dwyl](https://hex.pm/users/dwyl) as a co-owner of the `b58` package on Hex.pm  https://hex.pm/packages/b58
![image](https://user-images.githubusercontent.com/194400/80288209-56a32800-872e-11ea-83eb-118d7c6e6122.png)

That way we can publish a new version when needed. 📦 
Thanks! ☀️

**Comment by SimonLab** [comment]
done:
![image](https://user-images.githubusercontent.com/6057298/80363648-6d579500-887c-11ea-8e1e-75ad957ecf49.png)

The command to add a owner to the package is `mix hex.owner add b58 dwyl`
You can see the list of commands linked to hex with `mix hex --help`:

![image](https://user-images.githubusercontent.com/6057298/80363798-a7289b80-887c-11ea-925a-1a13dff91c8d.png)

**Comment by nelsonic** [comment]
Thanks @SimonLab 👍 
Could try and publish a new version once the PR #17 is merged. 💭

**Comment by nelsonic** [comment]
https://hex.pm/users/dwyl
![hex-pm-b58-package](https://user-images.githubusercontent.com/194400/80368784-2e7a0d00-8885-11ea-9aaf-c864f555b00d.png)

**Comment by nelsonic** [comment]
Published new version: https://hex.pm/packages/b58
![image](https://user-images.githubusercontent.com/194400/80378455-9be16a00-8894-11ea-9a1a-d846174b97ef.png)

**Comment by nelsonic** [comment]
Thanks @SimonLab ☀️
