### ISSUE TITLE
Combine alphanum fct and @alnum value

### ISSUE THREAD

**Issue by SimonLab** [dwyl/base58#18]
The library contains two representations of the characters set of base58:

https://github.com/dwyl/base58/blob/e817934107172f159cc65a638e792a227b2fdca2/lib/base58.ex#L63-L68

and a charlist created with the sigil `~c`:
https://github.com/dwyl/base58/blob/e817934107172f159cc65a638e792a227b2fdca2/lib/base58.ex#L93

I think it's possible to only use the sigil version. We'll need to update the function `codes_to_string`:
https://github.com/dwyl/base58/blob/e817934107172f159cc65a638e792a227b2fdca2/lib/base58.ex#L71-L75

to 

```elixir
  defp codes_to_string(codes) do
    codes
    |> Enum.map(&<<Enum.at(@ alnum, &1)>>)
    |> Enum.join()
  end
```

**Comment by nelsonic** [comment]
@SimonLab good idea. thanks for tidying this up. 👍
