### ISSUE TITLE
Unchecked dependencies for environment test

### ISSUE THREAD

**Issue by nelsonic** [dwyl/base58#20]
Just tried to add `:b58` to my `deps` and run `mix deps.get` and got the following Error:
```
Unchecked dependencies for environment test:
* b58 (Hex package)
  the app file at "_build/test/lib/b58/ebin/b58.app" is invalid
** (Mix) Can't continue due to errors on dependencies
```
![image](https://user-images.githubusercontent.com/194400/80419782-a837e800-88d1-11ea-8ba0-fd5e24f8c218.png)

Ran:

```
mix deps.clean --all
```

Followed by:

```
mix deps.get
```

Still fails:
![image](https://user-images.githubusercontent.com/194400/80420402-9efb4b00-88d2-11ea-8a67-cb53c9acf510.png)

I think the "app" needs to be `Base58` instead of `b58` for this to work.
@SimonLab can you please take a quick look at it tomorrow morning?  (Thanks!)

**Comment by SimonLab** [comment]
@nelsonic I've added the dependency to a new elixir project and didn't have any issue with getting the dependency with `mix deps.get` and running the `encode` and `decode` function.

You can try to delete the folders `deps`, `build` and the `mix.lock` file.
Then you can run `mix deps.get` and to make sure the project is build run `mix compile`

Hopefully this will fix the error.

**Comment by nelsonic** [comment]
@SimonLab testing that now. 👍

**Comment by SimonLab** [comment]
I've now got the error also. I've tried to install a previous version of b58 and can't compile it at the moment

**Comment by nelsonic** [comment]
```
rm mix.lock
rm -rf _build
rm -rf deps
mix deps.get
mix test
```

Still get:
```
Generated phoenix_ecto app
==> auth
Unchecked dependencies for environment test:
* b58 (Hex package)
  the app file at "_build/test/lib/b58/ebin/b58.app" is invalid
** (Mix) Can't continue due to errors on dependencies
```

**Comment by nelsonic** [comment]
It's going to be easier to diagnose this _after_ the Auth PR is finished. 
Looks like I need to update Phoenix: https://travis-ci.org/github/dwyl/auth/builds/680535522#L384

Let's come back to this in a couple of days when the Auth PR is done. 👍

**Comment by nelsonic** [comment]
@SimonLab once https://github.com/dwyl/auth/pull/43 is merged, please pick this up again. 🙏

**Comment by samhstn** [comment]
I'm seeing the same error on my machine. I managed to replicate it with:

```
mix new example
cd example
# add `{:b58, "~> 1.0"}` to `deps`.
mix do deps.get, compile
```

```
Resolving Hex dependencies...
Dependency resolution completed:
New:
  b58 1.0.1
* Getting b58 (Hex package)
==> B58
Compiling 1 file (.ex)
Generated B58 app
==> hello
Unchecked dependencies for environment dev:
* b58 (Hex package)
  the app file at "_build/dev/lib/b58/ebin/b58.app" is invalid
** (Mix) Can't continue due to errors on dependencies
```

If we look in `_build/dev/lib/b58/ebin`, we instead see a `B58.app` file.

I recon that if we change `B58` to `b58` [here](https://github.com/dwyl/base58/blob/master/mix.exs#L6), and release the change on hex, it could fix the problem.

Worth a try @nelsonic?

**Comment by nelsonic** [comment]
@samhstn should we publish a new version to Hex.pm now that #25 is merged?

**Comment by samhstn** [comment]
I think we should target being able to run `mix deps.get` and the `deps/b58/mix.exs` project config having `app: :b58` (instead of `app: :B58`). Then, when we compile, I think we shouldn't get this error any more.

I think publishing a new version is the way to do this.

**Comment by AurelienFT** [comment]
@nelsonic Still have the problem any update ?

**Comment by nelsonic** [comment]
@AurelienFT thanks for reminding us about this! Glad to know it's useful to someone `else`. 🙌 
I've _just_ published a new version to Hex.pm:  https://hex.pm/packages/b58/1.0.2 based on @samhstn's suggestion. 📦 
Please try it out and let us know how you get on. 🤞

**Comment by AurelienFT** [comment]
@nelsonic it's working with 1.0.2 ! Thank you

**Comment by nelsonic** [comment]
@AurelienFT thanks for confirming. ✅ 
Thanks to @samhstn for his Elixir knowledge/skills! 🙌
