### ISSUE TITLE
Use Github actions instead of Travis

### ISSUE THREAD

**Issue by SimonLab** [dwyl/base58#32]
![image](https://github.com/dwyl/base58/assets/6057298/1fa2cc25-ef78-4c16-abb2-6349c8cb365f)

The build badge from Travis doesn't work anymore.
We have switch to Github action to run tests when PRs are open on other Elixir project, we can now update this projects in a similar way and remove Travis

**Comment by nelsonic** [comment]
![image](https://github.com/dwyl/base58/assets/194400/40510288-a8b5-45e1-b01f-9c0fdbaa70f7)

Thanks again @SimonLab 👍
