### ISSUE TITLE
How to compile and run a C script with Elixir?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/base58#4]
ref: https://github.com/dwyl/base58encode/issues/1#issuecomment-458912961

For property-based-testing we'd like to compare our module to the result of the C base58 result function.
- [ ] For that we first need to compile the C code and run it with Elixir

reading: 
- https://andrealeopardi.com/posts/using-c-from-elixir-with-nifs/ 
- https://www.theerlangelist.com/article/outside_elixir

**Comment by SimonLab** [comment]
This needs a bit more research (and focus) to do this correctly. I also can see some issues with Travis, we need first to be able to understand how to compile/run the code on a local machine then we need to understand how to configure Travis to be able to run the tests.

**Comment by nelsonic** [comment]
Closing as the tests are adequate. ✅
