### ISSUE TITLE
Add images to Readme

### ISSUE THREAD

**Issue by SimonLab** [dwyl/base58#6]
The Readme is text only at the moment.
To make it a bit less dry and to explain the main ideas of base58 we could add some images.
A schema which represents how a string is converted to base 58 would be a good addition.

**Comment by nelsonic** [comment]
@Cleop we could use your _skillz_ on this. 🎨 
(_it would be a good test of whether the written docs + reference explain the idea well enough to translate it into a mini flow diagram etc... not "urgent" but a good "creative art practice" task..._)

**Comment by nelsonic** [comment]
Sadly, this was not completed at the time. Closing. 📕
